---
docker_compose_file:
  version: "3"
  services:
    app:
      container_name: "{{service_name}}-app"
      # depends_on:
      #   - database
      image: pinosaur/onigiri:latest
      expose:
        - "{{api_port}}"
      restart: always
    # database:
    #   container_name: onigiri-database
    #   image: surrealdb/surrealdb:latest
    #   ports:
    #     - 8000:8000
    #   volumes:
    #     - database-data:/data
    #   command: "start --log debug --user {{surreal_username}} --pass {{surreal_password}} memory"
    #   restart: always
  volumes:
    database-data: {}
  networks:
    default:
      name: karatnet
      external: true
