---
docker_compose_file:
  version: "3"
  services:
    app:
      container_name: "{{service_name}}-app"
      build: "{{playbook_dir}}/files"
      ports:
        - 80:80
        - 443:433
      restart: always
  networks:
    default:
      name: karatnet
      external: true
