---
- hosts: gentoo-distcc
  vars:
    make_threads: 4
    make_parallel_threads: 4
  tasks:
    - name: configure make.conf
      template:
        src: "{{playbook_dir}}/templates/make.conf.j2"
        dest: "/etc/portage/make.conf"
