---
docker_compose_file:
  version: "3"
  services:
    app:
      container_name: "{{service_name}}-app"
      build: "{{playbook_dir}}/files"
      volumes:
        - config:/etc/icecast2
      tty: true
      restart: always
  volumes:
    config: {}
  networks:
    default:
      name: karatnet
      external: true
