version: "3"
services:
  gitea:
    image: gitea/gitea:1.15.6-rootless
    environment:
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    volumes:
      - gitea-data:/var/lib/gitea
      - gitea-config:/etc/gitea
    ports:
      - "4002:3000"
      - "2222:2222"
    depends_on:
      - database
    restart: always

  database:
    image: postgres:13
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    volumes:
      - gitea-database:/var/lib/postgresql/data
    restart: always

volumes:
  gitea-data: {}
  gitea-config: {}
  gitea-database: {}
