---
docker_compose_file:
  version: "3"
  services:
    app:
      container_name: "{{service_name}}-app"
      image: searx/searx:latest
      environment:
        - "BIND_ADDRESS=0.0.0.0:{{service_port}}"
      expose:
        - "{{service_port}}"
      restart: always
  networks:
    default:
      name: karatnet
      external: true
