---
docker_compose_file:
  version: "3"
  services:
    app:
      container_name: "{{service_name}}-app"
      image: registry:2
      ports:
        - "{{service_port}}:{{service_port}}"
      volumes:
        - data:/var/lib/registry
      restart: always
  volumes:
    data: {}
  networks:
    default:
      name: karatnet
      external: true
