---
- hosts: local
  pre_tasks:
    - name: include public vars
      include_vars: "{{playbook_dir}}/vars/public.yml"
  tasks:
    - name: run docker compose
      docker_compose:
        project_name: "{{service_name}}"
        definition:
          version: "3"
          services:
            app:
              container_name: "{{service_name}}-app"
              build: "{{playbook_dir}}/files"
              expose:
                - "{{service_port}}"
              volumes:
                - data:/var/www/gitit/
              restart: always
          volumes:
            data: {}
          networks:
            default:
              name: karatnet
              external: true
