---
docker_compose_file:
  version: "3"
  services:
    # TODO we don't really need the web ui, maybe disable that
    # TODO how to pass --no-espeak flags etc so the docker image isnt mega choncc
    en:
      container_name: "{{service_name}}-en"
      image: synesthesiam/opentts:en
      expose:
        - "{{service_port}}"
      restart: always
    ja:
      container_name: "{{service_name}}-ja"
      image: synesthesiam/opentts:ja
      expose:
        - "{{service_port}}"
      restart: always
  networks:
    default:
      name: karatnet
      external: true

