---
- name: install ansible packages
  apt:
    update_cache: yes
    state: present
    pkg:
      - ansible
- name: install ansible community
  command: ansible-galaxy collection install community.general
- name: install ansible docker
  command: ansible-galaxy collection install community.docker
