---
- hosts: host
  pre_tasks:
    - name: include vars
      include_vars:
        dir: "{{playbook_dir}}/vars"
  tasks:
    - name: run docker compose
      docker_compose:
        project_name: "{{service_name}}"
        definition: "{{docker_compose_file}}"
        state: present
        build: yes

    # this needs to be copied into container
    # either mount a volume or just run docker cp using cmd module
    # - name: copy setting.yml
    #   template:
    #     src: "{{playbook_dir}}/templates/settings.yml.j2"
    #     dest: /etc/searx/settings.yml
    #     owner: root
    #     group: root
    #     mode: 0644

