---
docker_compose_file:
  version: "3"
  services:
    app:
      container_name: "{{service_name}}-app"
      build: "{{playbook_dir}}/files"
      expose:
        - "{{service_port}}"
      volumes:
        - config:/etc/lighttpd
        - /etc/letsencrypt:/etc/letsencrypt/
      restart: always
      tty: true
  volumes:
    config: {}
  networks:
    default:
      name: karatnet
      external: true
