---
docker_compose_file:
  version: "3"
  services:
    app:
      container_name: "{{service_name}}-app"
      build: "{{playbook_dir}}/files"
      volumes:
        - challenge:/letsencrypt
        - cert:/etc/letsencrypt
      restart: always
  volumes:
    challenge: {}
    cert: {}
