---
- hosts: host
  pre_tasks:
    - name: include vars
      include_vars:
        dir: "{{playbook_dir}}/vars"
  tasks:
    - name: create temp build directory
      tempfile:
        state: directory
        suffix: build
      register: builddir
    - name: copy build files
      copy:
        src: "{{playbook_dir}}/files/"
        dest: "{{builddir.path}}"
    - name: copy icecast config file
      template:
        src: "{{playbook_dir}}/templates/icecast.xml.j2"
        dest: "{{builddir.path}}/icecast.xml"
      become: yes
    - name: copy mpd config file
      template:
        src: "{{playbook_dir}}/templates/mpd.conf.j2"
        dest: "{{builddir.path}}/mpd.conf"
      become: yes
    - name: build radio container
      docker_image:
        name: localhost:5000/radio
        build:
          path: "{{builddir.path}}"
        push: yes
        tag: v1
        source: build
    - name: clean up
      file:
        state: absent
        path: "{{builddir.path}}"

