---
- name: create dev user with sudo
  user:
    name: "{{dev_username}}"
    # password: "{{dev_password | password_hash('sha512')}}"
    # update_password: on_create
    shell: /bin/bash
    groups: sudo
    append: yes
    create_home: yes
    state: present
- name: install basic packages
  apt:
    update_cache: yes
    pkg:
      - git
      - ufw
      - python3-pip
