---
# very similar to docker.yml, except this is used for running kubernetes nodes
- name: install containerd dependencies
  apt:
    update-cache: yes
    state: present
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common 
- name: add gpg key for docker repo
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
- name: add to apt sources
  apt_repository:
    repo: deb https://download.docker.com/linux/debian bullseye stable
    state: present
- name: install containerd packages
  apt:
    update_cache: yes
    state: present
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
- name: add dev user to docker group
  user:
    name: "{{dev_username}}"
    groups: docker
    append: yes
- name: remove cri from disabled plugins in containerd config.toml
  shell: sed -i 's/disabled_plugins = \["cri"\]/disabled_plugins = \[\]/' /etc/containerd/config.toml
- name: start and enable containerd service
  systemd:
    name: containerd
    state: started
    enabled: yes
- name: run kubeadm init
  shell: kubeadm init

