---
# TODO disable swap (figure out way to do this permanetley)

# very similar to docker.yml, except this is used for running kubernetes nodes
- name: install containerd dependencies
  apt:
    update-cache: yes
    state: present
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common 
- name: add gpg key for docker repo
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
- name: add to apt sources
  apt_repository:
    repo: deb https://download.docker.com/linux/debian bullseye stable
    state: present
- name: install containerd packages
  apt:
    update_cache: yes
    state: present
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
- name: add dev user to docker group
  user:
    name: "{{dev_username}}"
    groups: docker
    append: yes
- name: remove cri from disabled plugins in containerd config.toml
  shell: sed -i 's/disabled_plugins = \["cri"\]/disabled_plugins = \[\]/' /etc/containerd/config.toml

# TODO also add following lines to /etc/containerd/config.toml
# [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
#     [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
#         SystemdCgroup = true
- name: start and enable containerd service
  systemd:
    name: containerd
    state: restarted
    enabled: yes

# add following to /etc/ufw/sysctl.conf
#   net/bridge/bridge-nf-call-ip6tables = 1
#   net/bridge/bridge-nf-call-iptables = 1
#   net/bridge/bridge-nf-call-arptables = 1
