---
# TODO run these checks https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/ before starting node
- name: install kubernetes dependencies
  apt:
    update-cache: yes
    state: present
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
- name: add gpg key for kubernetes repo
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
- name: add to apt sources
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
- name: install kubernetes packages
  apt:
    update-cache: yes
    state: present
    pkg:
      - kubelet
      - kubeadm
      - kubectl
  # TODO also need to hold versions for these packages https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

# kubernetes control pane ports https://kubernetes.io/docs/reference/ports-and-protocols/
- ufw:
    comment: kubernetes API server
    rule: allow
    port: 6443
    proto: tcp
- ufw:
    comment: etcd server client API
    rule: allow
    port: 2379:2380
    proto: tcp
- ufw:
    comment: kubelet API
    rule: allow
    port: 10250
    proto: tcp
- ufw:
    comment: kube-scheduler
    rule: allow
    port: 10259
    proto: tcp
- ufw:
    comment: kube-controller-manager
    rule: allow
    port: 10257
    proto: tcp

# - name: run kubeadm init
#   shell: kubeadm init --skip-phases=kubelet-finalize --pod-network-cidr=192.168.0.0/16 --apiserver-advertise-address={MASTER NODE IP (192.168.1.101) for sendai}

# TODO run post kubeadm stuff (as dev user)
# mkdir -p $HOME/.kube
# sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
# sudo chown $(id -u):$(id -g) $HOME/.kube/config

# troubleshooting if `kubectl get all` cant connect to port 443
# just run `systemctl restart kubelet`

