---
docker_compose_file:
  version: "3"
  services:
    app:
      container_name: "{{service_name}}-app"
      image: gitea/gitea:1.15.6-rootless
      environment:
        - "GITEA__database__DB_TYPE={{database_type}}"
        - "GITEA__database__HOST=database:5432"
        - "GITEA__database__NAME={{database_name}}"
        - "GITEA__database__USER={{database_user}}"
        - "GITEA__database__PASSWD={{database_password}}"
      volumes:
        - app-config:/etc/gitea
        - app-data:/var/lib/gitea
        - /etc/timezone:/etc/timezone:ro
        - /etc/localtime:/etc/localtime:ro
      expose:
        - 3000
      ports:
        - "2222:2222"
      depends_on:
        - database
      restart: always
    database:
      container_name: "{{service_name}}-database"
      image: postgres:13
      environment:
        - "POSTGRES_DB={{database_name}}"
        - "POSTGRES_USER={{database_user}}"
        - "POSTGRES_PASSWORD={{database_password}}"
      volumes:
        - database-data:/var/lib/postgresql/data
      restart: always
  volumes:
    app-config: {}
    app-data: {}
    database-data: {}
  networks:
    default:
      name: karatnet
      external: true

