---
docker_compose_file:
  version: "3"
  services:
    en:
      container_name: "{{service_name}}-en"
      image: alphacep/kaldi-en:latest
      ports:
        - "{{service_port}}:{{service_port}}"
      restart: always
    # no container for japanese yet :[
  networks:
    default:
      name: karatnet
      external: true

