---
old_docker_compose_file:
  version: "3"
  services:
    app:
      container_name: "{{service_name}}-app"
      image: envoyproxy/envoy-alpine:v1.20.1
      ports:
        - 80:80
        - 443:443
      volumes:
        - config:/etc/envoy
        - /etc/letsencrypt:/etc/letsencrypt
      restart: always
  volumes:
    config: {}
  networks:
    default:
      name: karatnet
      external: true
