---
services:
  - {cluster: "searx", url: "searx.pinohacks.xyz", enabled: "true"}
  - {cluster: "codimd", url: "md.pinohacks.xyz", enabled: "true"}
  - {cluster: "gitit", url: "wiki.pinohacks.xyz", enabled: "true"}
  - {cluster: "gitea", url: "git.pinohacks.xyz", enabled: "true"}
  - {cluster: "kanboard", url: "todo.pinohacks.xyz", enabled: "true"}
