---
- hosts: local
  pre_tasks:
    - name: include public vars
      include_vars: "{{ playbook_dir }}/vars/public.yml"
    - name: include private vars
      include_vars: "{{ playbook_dir }}/vars/private.yml"
  tasks:
    # this doesnt work :(
    # - name: run docker compose
    #   docker_compose:
    #     project_name: "{{ service_name }}"
    #     state: absent
