---
docker_compose_file:
  version: "3"
  services:
    app:
      container_name: "{{service_name}}-app"
      image: localhost:5000/radio:v1
      volumes:
        - icecast-config:/etc/icecast2
        - mpd-config:/etc/mpd
      tty: true
      expose: 
        - "{{service_port}}"
      restart: always
  volumes:
    icecast-config: {}
    mpd-config: {}
  networks:
    default:
      name: karatnet
      external: true
