---
- hosts: local
  pre_tasks:
    - name: include vars
      include_vars:
        dir: "{{playbook_dir}}/vars"
  tasks:
    - name: check existence of /etc/letsencrypt
      stat:
        path: /etc/letsencrypt
      register: letsencrypt_dir
    - name: create /etc/letsencrypt
      file:
        state: directory
        path: /etc/letsencrypt
      when: letsencrypt_dir.stat.exists == false
      become: yes
    - name: run docker compose
      docker_compose:
        project_name: "{{service_name}}"
        definition: "{{docker_compose_file}}"
        state: present
        build: yes
