---
- hosts: node
  become: yes
  vars:
    dev_username: dev
    compose_version: v2.2.2
    docker_network: karatnet
  tasks:
    - include_tasks: "{{playbook_dir}}/tasks/{{item}}.yml"
      loop:
        - basic
        - docker
        - ufw
        - ansible

    # set ufw rules
    - ufw:
        rule: allow
        name: OpenSSH
    - ufw:
        rule: allow
        port: 80
    - ufw:
        rule: allow
        port: 443
    - ufw:
        rule: allow
        port: 51820
        proto: udp
