---
- hosts: sendai
  become: yes
  vars:
    dev_username: dev
    compose_version: v2.2.2
    docker_network: karatnet
  tasks:
    - include_tasks: "{{playbook_dir}}/tasks/{{item}}.yml"
      loop:
        # - basic
        # - ansible
        # - ufw
        - containerd
        - kubernetes
