---
- hosts: sendai
  become: yes
  vars:
    dev_username: dev
    compose_version: v2.2.2
    docker_network: karatnet
  tasks:
    - include_tasks: "{{playbook_dir}}/tasks/{{item}}.yml"
      loop:
        # - basic
        # - ansible
        # - ufw
        - containerd
        # - kubernetes

    # set ufw rules
    - ufw:
        rule: allow
        name: OpenSSH
    - ufw:
        rule: allow
        port: 80
    - ufw:
        rule: allow
        port: 443

    # kubernetes control pane ports https://kubernetes.io/docs/reference/ports-and-protocols/
    - ufw:
        comment: kubernetes API server
        rule: allow
        port: 6443
        proto: tcp
    - ufw:
        comment: etcd server client API
        rule: allow
        port: 2379:2380
        proto: tcp
    - ufw:
        comment: kubelet API
        rule: allow
        port: 10250
        proto: tcp
    - ufw:
        comment: kube-scheduler
        rule: allow
        port: 10259
        proto: tcp
    - ufw:
        comment: kube-controller-manager
        rule: allow
        port: 10257
        proto: tcp

