---
docker_compose_file:
  version: "3"
  services:
    app:
      container_name: "{{service_name}}-app"
      image: hackmdio/hackmd:2.4.1
      environment:
        - "CMD_DB_URL=postgres://{{postgres_user}}:{{postgres_pass}}@codimd-database/{{postgres_db}}"
        - "CMD_SESSION_SECRET={{session_secret}}"
        - "CMD_USECDN=false"
        - "CMD_EMAIL=true"
        - "CMD_ALLOW_EMAIL_REGISTER=false"
        - "CMD_ALLOW_ANONYMOUS=false"
        - "CMD_ALLOW_ANONYMOUS_EDITS=false"
        - "CMD_ALLOW_ANONYMOUS_VIEWS=false"
        - "CMD_DEFAULT_PERMISSION=true"
        - "CMD_ALLOW_GRAVATAR=true"
        - "CMD_ALLOW_FREEURL=false"
        - "CMD_ALLOW_PDF_EXPORT=true"
      depends_on:
        - database
      expose:
        - "{{service_port}}"
      volumes:
        - app-data:/home/hackmd/app/public/uploads
      restart: always
    database:
      container_name: "{{service_name}}-database"
      image: postgres:11.6-alpine
      environment:
        - "POSTGRES_USER={{postgres_user}}"
        - "POSTGRES_PASSWORD={{postgres_pass}}"
        - "POSTGRES_DB={{postgres_db}}"
      volumes:
        - database-data:/var/lib/postgresql/data
      restart: always
  volumes:
    database-data: {}
    app-data: {}
  networks:
    default:
      name: karatnet
      external: true

